<?php

/**
 * sfGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobee
 * @subpackage model
 * @author     Walter Devia <walter.devia@outlook.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardGroup extends PluginsfGuardGroup
{

}