<?php

/**
 * JobeetCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginJobeetCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobeetCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetCategory');
    }

    public function getWithJobs()
    {
      // This query seems like it don't return categories and jobs
      // instead it just return categories but the ones that have at minimun
      // one job non expired
      // $q = $this->createQuery('c')
      //   ->leftJoin('c.JobeetJobs j')
      //   ->where('j.expires_at > ?', date('Y-m-d H:i:s', time()));
      //   // ->orderBy('c.name');

      // $q->andWhere('j.is_activated = ?', 1);

      $q = $this->createQuery('c')
        ->leftJoin('c.Translation t')
        ->leftJoin('c.JobeetJobs j')
        ->where('j.expires_at > ?', date('Y-m-d H:i:s', time()))
        ->orderBy('t.name');
   
      return $q->execute();
    }

    public function doSelectForSlug($parameters)
    {
      return $this->findOneBySlugAndCulture($parameters['slug'], $parameters['sf_culture']);
    }
     
    public function findOneBySlugAndCulture($slug, $culture = 'en')
    {
      $q = $this->createQuery('a')
        ->leftJoin('a.Translation t')
        ->andWhere('t.lang = ?', $culture)
        ->andWhere('t.slug = ?', $slug);
      return $q->fetchOne();
    }
     
    public function findOneBySlug($slug)
    {
      return $this->findOneBySlugAndCulture($slug, 'en');
    }
}
