<?php

/**
 * JobeetCategoryAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetCategoryAffiliateTable extends PluginJobeetCategoryAffiliateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobeetCategoryAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetCategoryAffiliate');
    }
}